---
name:             GeometryAPI
main:             presentkim\geometryapi\GeometryAPI
version:          1.0.0
api:              [3.0.0, 3.0.0-ALPHA10]
author:           PresentKim

permissions:
  geometryapi.cmd:
    description:  GeometryAPI main command
    default:      op
    children:
      geometry.cmd.list:
        description:  GeometryAPI command - list
        default:      op
      geometry.cmd.lang:
        description:  GeometryAPI command - lang
        default:      op
      geometry.cmd.reload:
        description:  GeometryAPI command - reload
        default:      op
      geometry.cmd.save:
        description:  GeometryAPI command - save
        default:      op
...
