---
name:             GeometryAPI
main:             kim\present\geometryapi\GeometryAPI
version:          1.0.2
api:              [3.0.0, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12, 4.0.0]
author:           PresentKim
website:          https://github.com/PresentKim/GeometryAPI-PMMP
description:      A plugin skin geometry data api

permissions:
  geometry.cmd:
    description:  Show skin geometry list
    default:      op
...
