---
name:             GeometryAPI
main:             blugin\geometryapi\GeometryAPI
version:          1.0.2
api:              [3.0.0, 3.0.0-ALPHA10, 3.0.0-ALPHA11]
author:           PresentKim
website:          https://github.com/PMMPPlugin/GeometryAPI
description:      A plugin skin geometry data api

permissions:
  geometryapi.cmd:
    description:  GeometryAPI main command
    default:      op
    children:
      geometry.cmd.list:
        description:  GeometryAPI command - list
        default:      op
      geometry.cmd.lang:
        description:  GeometryAPI command - lang
        default:      op
...
